server:
  port: 8081
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /mp
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect:  org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url:  jdbc:postgresql://localhost:5432/weixin
    username: weixin
    password: 123456
    driverClassName: org.postgresql.Driver
logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG
