server:
  port: 10101
zuul:
  routes:
#    front:
#      path: /wechat/front/**
#      url: http://localhost:4200
    api:
      path: /wechat/api/**
      url: http://localhost:8080/api
    portal:
      path: /wechat/portal/**
      url: http://localhost:8080/portal
    auth:
      path: /wechat/auth/**
      url: http://localhost:8080/auth
logging:
  level:
    org.springframework.security: DEBUG